### ISSUE TITLE
Use of other spoken languages

### ISSUE THREAD

**Issue by HDelpr** [cucumber/vscode#141]
### 🤔 What's the problem you're trying to solve?

Using SpecFlow (and Cucumber) in The Netherlands I often use dutch for my feature files. 
To give none development team members te possibility to contribute to the feature files vscode is een goed tool.
Having the highlighting of the Cucumber plugin whould be even more usefull. But as far as I figured out is does not suport the (spoken) languages of https://cucumber.io/docs/gherkin/languages/.  

### ✨ What's your proposed solution?

Make it possible to use these supported languages.
Even adding the possibility to ad the translation tabel as shown on the https://cucumber.io/docs/gherkin/languages/ in the vscode/cucumber plug-in settings whould be aan improvement. 

#### Examples
**Visual studio shows:**
![image](https://user-images.githubusercontent.com/122610422/212313698-6c82aa8d-9ff9-4e1f-9b0b-12523bc85bd1.png)

And

![image](https://user-images.githubusercontent.com/122610422/212314480-070e0e35-ea45-4414-9a53-387e907e5b2a.png)

**vscode with Cucumber plug-in shows:**
![image](https://user-images.githubusercontent.com/122610422/212314058-234cfa59-693d-4fa9-8306-5e1b3194f4d2.png)
 
Instead of someting like:
![image](https://user-images.githubusercontent.com/122610422/212314205-c1b939b3-4d84-4a33-a0fe-43d0d70d2b05.png)

**Comment by kieran-ryan** [comment]
Thanks for your contributions @HDelpr and @tulavalle in raising - have added some [initial documentation on gherkin localisation to the README](https://github.com/cucumber/vscode#gherkin-localisation) arising from your issues. 🙌

This would be a SpecFlow deviation rather than Cucumber.

An initial observation is that the Cucumber localisation documentation was copied over to SpecFlow documentation without the necessary information to indicate incompatibilities; [SpecFlow dialects documentation](https://docs.specflow.org/projects/specflow/en/latest/Gherkin/Gherkin-Reference.html#gherkin-dialects) states:

> **Note** Big parts of this page where taken over from https://cucumber.io/docs/gherkin/reference/.

The Cucumber ecosystem (including this extension) adhere to the keys for spoken languages in the Cucumber [gherkin parser repository](https://github.com/cucumber/gherkin/blob/main/gherkin-languages.json) - which the [localisation documentation](https://cucumber.io/docs/gherkin/languages/) is created from. Note, it does not contain an `nl-NL`, `en-US` or `pt-BR` key. For example, using the `nl` key specified in the localisation documentation will work for you:

```gherkin
# language: nl
Functionaliteit: Rekenmachine

  @mytag
  Scenario: twee getallen optellen
    Stel I have an "expression"
    En het tweede getal 70 is
    Als de twee getallen opgeteld zijn
    Dan is het resultaat 120
```

In the [SpecFlow Configuration Elements documentation](https://docs.specflow.org/projects/specflow/en/latest/Installation/Configuration.html#configuration-elements), building on the aforementioned gherkin localisation documentation, they "recommend using specific culture names (e.g.: “en-US”) rather than generic (neutral) cultures (e.g.: “en”)" - this appears to be driven by how SpecFlow is implemented. This SpecFlow deviation is not supported by the gherkin parser and will raise a parsing error, see below example:

```python
from gherkin.parser import Parser
from gherkin.pickles.compiler import Compiler

parser = Parser()
gherkin_document = parser.parse(
"""
# language: nl-NL
Functionaliteit: Rekenmachine
"""
)
pickles = Compiler().compile(gherkin_document)
```

```console
...
gherkin.errors.CompositeParserException: Parser errors:
(2:1): Language not supported: nl-NL
```

### Actions

Considering the extension supports the [gherkin spoken languages localisation](https://cucumber.io/docs/gherkin/languages/), I have closed the issue. However I was wondering @HDelpr/@tulavalle whether you can advise if not following the 'recommendation' of SpecFlow of using 'specific culture names' has any impact on your SpecFlow testing i.e. using the global names such as `en`, `nl` and `pt`? If no issue, the extension should be compatible with your gherkin and also with SpecFlow testing.

Otherwise, I would suggest to open an issue with [SpecFlow](https://github.com/SpecFlowOSS/SpecFlow) to support the keys from the [gherkin localisation documentation](https://cucumber.io/docs/gherkin/languages/); or alternatively to raise an issue on the [gherkin parser repository](https://github.com/cucumber/gherkin/tree/main) to support specific culture keys.

Hope this provides some clarity, but please comment if any queries, etc. There is definitely scope to improve documentation on this topic for both Cucumber and SpecFlow so interested in any thoughts. Cheers!

**Comment by tulavalle** [comment]
> Thanks for your contributions @HDelpr and @tulavalle in raising - have added some [initial documentation on gherkin localisation to the README](https://github.com/cucumber/vscode#gherkin-localisation) arising from your issues. 🙌
> 
> This would be a SpecFlow deviation rather than Cucumber.
> 
> An initial observation is that the Cucumber localisation documentation was copied over to SpecFlow documentation without the necessary information to indicate incompatibilities; [SpecFlow dialects documentation](https://docs.specflow.org/projects/specflow/en/latest/Gherkin/Gherkin-Reference.html#gherkin-dialects) states:
> 
> > **Note** Big parts of this page where taken over from https://cucumber.io/docs/gherkin/reference/.
> 
> The Cucumber ecosystem (including this extension) adhere to the keys for spoken languages in the Cucumber [gherkin parser repository](https://github.com/cucumber/gherkin/blob/main/gherkin-languages.json) - which the [localisation documentation](https://cucumber.io/docs/gherkin/languages/) is created from. Note, it does not contain an `nl-NL`, `en-US` or `pt-BR` key. For example, using the `nl` key specified in the localisation documentation will work for you:
> 
> ```
> # language: nl
> Functionaliteit: Rekenmachine
> 
>   @mytag
>   Scenario: twee getallen optellen
>     Stel I have an "expression"
>     En het tweede getal 70 is
>     Als de twee getallen opgeteld zijn
>     Dan is het resultaat 120
> ```
> 
> In the [SpecFlow Configuration Elements documentation](https://docs.specflow.org/projects/specflow/en/latest/Installation/Configuration.html#configuration-elements), building on the aforementioned gherkin localisation documentation, they "recommend using specific culture names (e.g.: “en-US”) rather than generic (neutral) cultures (e.g.: “en”)" - this appears to be driven by how SpecFlow is implemented. This SpecFlow deviation is not supported by the gherkin parser and will raise a parsing error, see below example:
> 
> ```python
> from gherkin.parser import Parser
> from gherkin.pickles.compiler import Compiler
> 
> parser = Parser()
> gherkin_document = parser.parse(
> """
> # language: nl-NL
> Functionaliteit: Rekenmachine
> """
> )
> pickles = Compiler().compile(gherkin_document)
> ```
> 
> ```
> ...
> gherkin.errors.CompositeParserException: Parser errors:
> (2:1): Language not supported: nl-NL
> ```
> 
> ### Actions
> Considering the extension supports the [gherkin spoken languages localisation](https://cucumber.io/docs/gherkin/languages/), I have closed the issue. However I was wondering @HDelpr/@tulavalle whether you can advise if not following the 'recommendation' of SpecFlow of using 'specific culture names' has any impact on your SpecFlow testing i.e. using the global names such as `en`, `nl` and `pt`? If no issue, the extension should be compatible with your gherkin and also with SpecFlow testing by using those keys.
> 
> Otherwise, I would suggest to open an issue with [SpecFlow](https://github.com/SpecFlowOSS/SpecFlow) to support the keys from the [gherkin localisation documentation](https://cucumber.io/docs/gherkin/languages/); or alternatively to raise an issue on the [gherkin parser repository](https://github.com/cucumber/gherkin/tree/main) to support additional specific culture keys.
> 
> Hope this provides some clarity, but please comment if any queries, etc. There is definitely scope to improve documentation on this topic for both Cucumber and SpecFlow so interested in any thoughts. Cheers!

The added documentation regarding the required settings helped resolve the issue. All you had to do was apply them in settings.json. As I use Specflow, the language configuration was being done by specflow.json. After configuration, for the extension to identify the feature files, it was enough to include the language indication in each file "*.feature. In the case of Brazilian Portuguese, specifying (pt-BR) does not work, however, leaving it generic I was able to use the extension without problems: "# language: pt". Another one did it, thanks for your attention @kieran-ryan!

**Comment by kieran-ryan** [comment]
Thanks for the valuable feedback @tulavalle! If you encounter further issues or have any feature request ideas while using the extension, feel free to raise and we'll take a look. Thanks! 🙌
