### ISSUE TITLE
Missing Binary Operator 

### ISSUE THREAD

**Issue by gnturbo** [cucumber/vscode#156]
Hi, I'm new to this and could use some help in configuring the Firmware for my Ender 6. 

I am getting the following error in VS Code and don't know how to correct it? Any help would be greatly appreciated! 

buildroot/share/PlatformIO/scripts/../../../../Marlin/src/inc/../../Configuration.h:155:12: error: missing binary operator before token "("
  155 | #if ENABLE (CUSTOM_PROBE)
      |            ^

**Comment by kieran-ryan** [comment]
Hi @gnturbo, thank you for raising, is there any more information you could provide and hopefully we can help to resolve the issue? Information that can be useful can include:

- [Visual Studio Code version](https://code.visualstudio.com/docs/supporting/FAQ#_how-do-i-find-the-version) 
- [Cucumber extension version](https://marketplace.visualstudio.com/items?itemName=CucumberOpen.cucumber-official)
  - any [extension settings](https://github.com/cucumber/vscode#extension-settings) set in the workspace or in Visual Studio Code user settings
- an example feature files relating to the issue - along with their file path in your workspace
- an example step definition relating to the issue - along with their file path in your workspace
- the output of the Cucumber Language Server in the [output window](https://learn.microsoft.com/en-us/visualstudio/ide/reference/output-window?view=vs-2022#:~:text=To%20open%20the%20Output%20window,%3E%20Output%2C%20or%20press%20Ctrl%2BAlt%2BO.)

**Comment by kieran-ryan** [comment]
Based on the provided information and the [davidchandra/ender6config repository](https://github.com/davidchandra/ender6config), this issue appears to relate to configuration of firmware for the Ender 6 Marlin 3d printer; and to have been raised against the incorrect GitHub project.

Thus closing the issue, please advise if this is otherwise the case @gnturbo and we will reopen the issue. Thank you
