### ISSUE TITLE
Cucumber.io doesn't work properly on VS Code v1.78.2 

### ISSUE THREAD

**Issue by mweleyam** [cucumber/vscode#164]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 
<img width="251" alt="image" src="https://github.com/microsoft/vscode/assets/104407296/df751961-72e8-4f44-9e29-a6bd1dcab6eb">

- OS Version: 
<img width="579" alt="image" src="https://github.com/microsoft/vscode/assets/104407296/56d568e2-7cb4-40e5-b50f-6b6111de8349">

Steps to Reproduce:

1. Update VS code to 1.78.2
2. My Cucumber extension doesn't work properly when I update VS Code to v1.78.2
3. Show an error message like this
<img width="490" alt="image" src="https://github.com/microsoft/vscode/assets/104407296/41aca919-9308-474d-bacb-566f11dca418">

[Error - 12:47:10 PM] Server initialization failed.
  Message: Request initialize failed with message: abort(Assertion failed: bad export type for `tree_sitter_php_external_scanner_create`: undefined). Build with -s ASSERTIONS=1 for more info.
  Code: -32603 
[Error - 12:47:10 PM] Cucumber Language Server client: couldn't create connection to server.
  Message: Request initialize failed with message: abort(Assertion failed: bad export type for `tree_sitter_php_external_scanner_create`: undefined). Build with -s ASSERTIONS=1 for more info.
  Code: -32603 

4. And my .feature file is like this (the color is black and white), I can't  jump to step files, when I click cmd+click on the step feature
<img width="650" alt="image" src="https://github.com/microsoft/vscode/assets/104407296/84c8f43a-ec8f-439f-8de9-9d9723f29904">

**Comment by tim-yao** [comment]
same issue as https://github.com/cucumber/vscode/issues/155

**Comment by ashishsarangi7** [comment]
Same issue...

**Comment by apenab** [comment]
Same issue...

**Comment by sijakret** [comment]
same here.. stopped working with the language server crashing..

**Comment by faaadly** [comment]
same issue, is there any update for the fix guys?

**Comment by selfrefactor** [comment]
uninstall the extension and subscribe to this topic - what else?

**Comment by mpweed** [comment]
To whom it may concern,

The extension is completely broken for me right now. Please provide:

- Acknowledgment of the issue.
- Status of the analysis and correction effort.

Thanks!

**Comment by The-BDD-Coach** [comment]
This has already been reported in Issue #155. @xeger has created a patched (hacked) version here: https://github.com/xeger/cucumber-vscode/releases/tag/v1.7.1 that fixes the problem, but it won't be released; you must download it and install it locally if you want to test it.

He considers this to be a hack because the real problem is in the tree-sitter code; it doesn't play well with Electron 22 and the latest version of V8. Once a new tree-sitter is released that fixes the problem we won't need the hack. The tree-sitter problem has been discusses extensively and there is an open PR that appears to fix it:
https://github.com/tree-sitter/node-tree-sitter/issues/126
https://github.com/tree-sitter/node-tree-sitter/pull/127

**Comment by fuentesjs** [comment]
Thank you for the patch.  It fixed the problem, and it connects to the server now.  Also, I added the Cucumber (Gherkin) full support.  For assertions, I am using TestNG.

**Comment by sagarvarulegit** [comment]
Wondering how it shows "Build: Passing" when installing Extension

**Comment by logesh-jarvis** [comment]
Any updates on this? We need this for some critical delivery!

**Comment by gopi2603** [comment]
Any update on this team? We're depending on this with critical delivery.

**Comment by The-BDD-Coach** [comment]
@logesh-jarvis @gopi2603 The best we can offer at the moment is the temporary fix that Xeger has provided. 

The best place to post questions like this is in the tree-sitter project; a proper fix is entirely dependent on a new release of tree-sitter (or maybe Web Tree-sitter).

**Comment by fa-gb** [comment]
> This has already been reported in Issue #155. @xeger has created a patched (hacked) version here: https://github.com/xeger/cucumber-vscode/releases/tag/v1.7.1 that fixes the problem, but it won't be released; you must download it and install it locally if you want to test it.
> 
> He considers this to be a hack because the real problem is in the tree-sitter code; it doesn't play well with Electron 22 and the latest version of V8. Once a new tree-sitter is released that fixes the problem we won't need the hack. The tree-sitter problem has been discussed extensively and there is an open PR that appears to fix it: [tree-sitter/node-tree-sitter#126](https://github.com/tree-sitter/node-tree-sitter/issues/126) [tree-sitter/node-tree-sitter#127](https://github.com/tree-sitter/node-tree-sitter/pull/127)

both seems closed, what is missing?

**Comment by jenisys** [comment]
@fa-gb 
The `node-tree-sitter#127` issue was split up into 4 issues/PRs, 2 are already merged and 2 are still open (see: Last statement of `#127` on split up).

**Comment by xeger** [comment]
We (at `cucumber/vscode`) are blocked until the TreeSitter team can make a new release of `node-tree-sitter` that works smoothly with Electron 22.

My hack is essentially to disregard missing WASM exports, which could cause crashes or undefined behavior if exports are _genuinely_ missing, as opposed to the exports merely appearing to be missing because of the Electron 22 + TreeSitter + WASM integration bug.

I am very hesitant to release any official `cucumber/vscode` build that uses the hack, because:
1. I don't understand the nature of the TreeSitter bug (why _do_ the exports seem to be missing)?
2. The hack literally monkey patches a TreeSitter distributable in order to ignore the Electron 22 issue.

My apologies on the delay, but the ball is in TreeSitter's court just now. In the meantime, my unofficial/hack build of the VS Code extension should help developers stay productive.

**Comment by riker09** [comment]
Thank you for keeping us up to date on this.

I am truly sorry for the additional noise this comment might cause for some people. But I really wanted to say thank you for developing this extension in the first place and everybody else for their patience on this.

**Comment by DerZyklop** [comment]
FTR: I assume @xeger means this: https://github.com/tree-sitter/tree-sitter/issues/2338

**Comment by xeger** [comment]
Good news everyone: Visual Studio Code has fixed the underlying bug with Electron and WASM, which means our extension will soon work again. I will publish 1.8.0 shortly.

<img width="992" alt="image" src="https://github.com/cucumber/vscode/assets/73368/0829bbd3-5c84-4500-8442-1d079ac36f6c">

**Comment by xeger** [comment]
This is fixed in [v1.8.0](https://github.com/cucumber/vscode/releases/tag/release%2Fv1.8.0) which should be published to the Visual Studio Code Marketplace soon, or you can install from the `.vsix` file in the linked release.

Note that you need to be using the Insider Release of Visual Studio Code until they release their September update.

**Comment by patrickschilder** [comment]
> This is fixed in [v1.8.0](https://github.com/cucumber/vscode/releases/tag/release%2Fv1.8.0) which should be published to the Visual Studio Code Marketplace soon, or you can install from the `.vsix` file in the linked release.
> 
> Note that you need to be using the Insider Release of Visual Studio Code until they release their September update.

Hi @xeger, when will this version be released to the marketplace? I saw that build failed: https://github.com/cucumber/vscode/actions/runs/6251011331

**Comment by xeger** [comment]
The Marketplace credentials are expired, so we can't publish the `.vsix` file to the official distribution channel. I'm working with other contributors to get them replaced; sorry I can't have a specific time frame, but "ASAP" is my goal.

In the meantime, you can visit the release's page in GitHub, download the `.vsix` file yourself, and install it using "Install from VSIX" in the Code UI:

![image](https://github.com/cucumber/vscode/assets/73368/fff35d34-513f-4552-96ef-47f04f0345fe)

**Comment by selfrefactor** [comment]
I celebrate that this issue is resolved and that we expect things to get back to working state. Still, installing release file in VSCode Insiders gives error - `Unable to install extension 'cucumberopen.cucumber-official' as it is not compatible with VS Code '1.81.0-insider'.`  Still, on regular `code` it does install.

**Comment by xeger** [comment]
@selfrefactor the underlying bug (which broke the extension) is an incompatibility between Electron and WASM. VS Code builds from 1.78 - 1.81 will never work with any version of this extension. I recommend upgrading to the latest Insider build, 1.83.
