### ISSUE TITLE
Auto Complete doesnt seem to work when using cypress

### ISSUE THREAD

**Issue by afcbpeter1** [cucumber/vscode#188]
### 👓 What did you see?
I've cloned this repo because I'd like to play around using cypress and cucumber.

https://github.com/eccanto/base-cypress-cucumber-typescript

However after installing the cucumber full support extension and doing npm i. I can't seem to get the glue to work on the feature file. Or in this case autocomplete.

Here is my settings.json any ideas?

```
{
    // Specify the directory where your step definitions are located
    "cucumberautocomplete.steps": [
      "cypress/e2e/steps/src/pages/*.ts",
      "cypress/e2e/steps/src/*.ts"
    ],
  
    // Enable strict Gherkin completion, ensuring consistent step definitions
    "cucumberautocomplete.strictGherkinCompletion": true,
  
    // Specify custom parameters to pass to your step definitions
    "cucumberautocomplete.customParameters": [
  
    ],
  
    // Define the directory where your feature files are located
    "cucumber.features": [
      "cypress/e2e/features"
    ],

    "cucumberautocomplete.syncfeatures": "cypress/e2e/features",
  
    // Set your preferred icon theme for the editor
    "workbench.iconTheme": "vscode-icons",
  }
```

### ✅ What did you expect to see?

I would expect to be able to go in to my step definition.

### 📦 Which tool/library version are you using?

Using VS code with Cypress and cucumber installed the cucumber full support extension.

### 🔬 How could we reproduce it?

1. Clone the above repo.
2. Add my settings to your vscode settings file.
3. See that the autocomplete hasn't worked

### 📚 Any additional context?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by kieran-ryan** [comment]
@afcbpeter1, it looks you may be using the [(Gherkin) Full Support extension](https://marketplace.visualstudio.com/items?itemName=alexkrechik.cucumberautocomplete) rather than the [official Cucumber extension](https://marketplace.visualstudio.com/items?itemName=CucumberOpen.cucumber-official) (this repository). However, one key in your configuration file does relate to this extension (`cucumber.features`).

To use this extension, you will need to update your glob pattern for feature files from `"cypress/e2e/features"` to `"cypress/e2e/features/**/*.feature"` and you will also need to add a `cucumber.glue` key with a glob pattern for your step definition files. You can find more information on these extension settings in the [README](https://github.com/cucumber/vscode#extension-settings).

Your settings file should appear as follows:

```json
{
    "cucumber.glue": [
        "cypress/e2e/steps/**/*.ts"
    ],
    "cucumber.features": [
        "cypress/e2e/features/**/*.feature"
    ]
}
```

If you'd like to try this out, I've pushed these changes to a [fork of the linked repository](https://github.com/kieran-ryan/base-cypress-cucumber-typescript/tree/a97397ea7cf9d1a28190f309c671ab5e0da3f3b0). Please advise if this enables the extension to work for you.
