### ISSUE TITLE
Steps marked undefined in Cypress project

### ISSUE THREAD

**Issue by viditasatam** [cucumber/vscode#231]
### 👓 What did you see?

I am using Cypress (13.9.0) with cucumber (cucumber.io) plugin in VSCode IDE.

My file structure for feature file is `cypress/e2e/features/SCC/*.feature`, file structure for step definition is `cypress/e2e/step_definitions/SCC/*.ts`

### tsconfig.json:

```json
"include": [
	"**/*.ts", 
	"cypress/e2e/step_definitions/**/*.ts",
	"cypress.config.js",
	"cypress/plugins/*"
],
```

### package.json:

```json
"cypress-cucumber-preprocessor": {
	"stepDefinitions": [
		"cypress/e2e/step_definitions/**/*.{js,ts}"
	],
	"nonGlobalStepDefinitions": false
},
```

When I run the feature file, it runs fine but feature file shows warning on each step and am unable to navigate to step def through feature file. Please suggest.

![image](https://github.com/cucumber/vscode/assets/47809990/3fec312c-25bd-4c4b-a4a4-b32eb7eecf06)
![image](https://github.com/cucumber/vscode/assets/47809990/5047a2f8-8c3a-410a-ab6c-7f6b313dc075)

### ✅ What did you expect to see?

Feature file steps should be glued to step definition file steps. Also I should be able to navigate to step def steps from feature files.

### 📦 Which tool/library version are you using?

"typescript": "^5.4.5"
"cypress": "^13.9.0",
"cypress-cucumber-preprocessor": "^4.3.1",
"@badeball/cypress-cucumber-preprocessor": "^20.0.5",

**Comment by kieran-ryan** [comment]
Hey @viditasatam, thanks for raising and appreciate your interest in the project! The extension provides default paths for locating [glue files](https://github.com/cucumber/vscode?tab=readme-ov-file#cucumberglue) and [feature files](https://github.com/cucumber/vscode?tab=readme-ov-file#cucumberfeatures) - following some typical project structures.

From the screenshots of your project, I observe your files would fall outside these default paths; thus some configuration of the extension is required. As a `.vscode` directory doesn't appear to be present in your project, I will make the assumption that the paths are yet to be configured in the workspace. I do observe `settings.json` in a tab, though suspect that may be for your user settings and while you could configure it from there, workspace settings may be better suited to your use case.

Inside your workspace in VSCode, can you create a `.vscode` directory containing a `settings.json` with the following configuration (see [a sample configuration](https://github.com/kieran-ryan/cucumber-env-samples/blob/main/.vscode/settings.json)); and advise whether resolves the issue?

```json
{
  "cucumber.features": [
    "cypress/e2e/features/**/*.feature"
  ],
  "cucumber.glue": [
    "cypress/e2e/step_definitions/**/*.js",
    "cypress/e2e/step_definitions/**/*.ts"
  ]
}
```

Should this not work, there are some known parsing issues with step definitions relating to TypeScript (e.g. cucumber/language-service#187); and if you could share some sample step definitions, I'd be happy to investigate the root cause of the issue and identify any work required to resolved.

**Comment by viditasatam** [comment]
Thanks. It works by adding this piece of code in my settings.json file :)

**Comment by kieran-ryan** [comment]
Delighted to hear that - thanks for the update @viditasatam!
