### ISSUE TITLE
After login to Microsoft Azure AD, unable to redirect back to base URL

### ISSUE THREAD

**Issue by viditasatam** [cucumber/vscode#241]
### 👓 What did you see?

I am working on a cypress+ cucumber project. There is a scenario where I login to a URL. I am prompted a Microsoft login popup. I am handling the popup, authenticating the otp, and expecting to go back to the URL and page to load but the URL does not load and the page is blank.

My cypress.config.js looks like:

```javascript
const { defineConfig } = require('cypress');
const createBundler = require("@bahmutov/cypress-esbuild-preprocessor");
const preprocessor = require("@badeball/cypress-cucumber-preprocessor");
const createEsbuildPlugin = require("@badeball/cypress-cucumber-preprocessor/esbuild");
const fs = require("fs");
const path = require("path");

module.exports = defineConfig({

	e2e: {
		chromeWebSecurity: false, 
		setupNodeEvents(on, config) {
			on("file:preprocessor",
				createBundler({
					plugins: [createEsbuildPlugin.default(config)],
				}));
			preprocessor.addCucumberPreprocessorPlugin(on, config);
			// require('cypress-mochawesome-reporter/plugin')(on);
			on("task", {
				log(message) {
					console.log(message)
					return null
				},
			});
			on("task", {
				verifyFileDownloaded(partialFileName) {
					const downloadDir = config.downloadsFolder || "cypress/downloads";
					const files = fs.readdirSync(downloadDir);
					return files.some((file) => file.includes(partialFileName));
				},
				clearDownloads() {
					const downloadDir = config.downloadsFolder || "cypress/downloads";
					fs.readdirSync(downloadDir).forEach((file) => {
						const filePath = path.join(downloadDir, file);
						fs.unlinkSync(filePath);
					});
					return null;
				}

			});

			return config;
		},

		baseUrl: "***",
		experimentalMemoryManagement: false,
		experimentalModifyObstructiveThirdPartyCode: true,
		experimentalOriginDependencies: false,
		modifyObstructiveCode: false,
		contentSecurityPolicy: false,
		trashAssetsBeforeRuns: true,
		watchForFileChanges: false,
		defaultCommandTimeout: 18000,
		numTestsKeptInMemory: 1,
		defaultCommandTimeout: 10000,
		pageLoadTimeout: 60000,
		specPattern: 'cypress/e2e/features/**/*.feature',
		reporter: 'mocha-multi-reporters',
		reporterOptions: {
			configFile: 'reporter-config.json',
		},
		viewportWidth: 1400,
		viewportHeight: 1080,
		downloadsFolder: "cypress/downloads",
	},
});
```

My login code looks like:

```javascript
	this.elements.continueBtn().click();
		// Verify window.open was called
		cy.get('@windowOpen').should('be.called');
		cy.get('@windowOpen').then((spy: any) => {
			const fullPopupUrl = spy.getCall(0).args[0]; // Extract URL from the first call
			const url = new URL(fullPopupUrl);

			// Extract necessary parameters
			const baseUrl = url.origin; // Extract base URL
			const path = url.pathname + url.search; // Extract path including search params

			// Use cy.origin() to handle commands on the new origin
			cy.origin(baseUrl, { args: { path } }, ({ path }) => {
				cy.visit(path, { timeout: 20000 }); // Increased timeout
				// Wait for the email input to be visible and interact
				cy.get('input[type=email]', { timeout: 10000 })
					.should('be.visible')
					.then((input) => {
						cy.wrap(input).type('***');
						cy.get('input[type=submit]').click();
						// Wait for the password input to be visible and interact
						cy.get('input[type=password]', { timeout: 10000 })
							.should('be.visible')
							.then((input) => {
								cy.wrap(input).type('***');
								cy.get('input[type=submit]').click();
							});
					});
			});

			// Check if redirected to the target URL
			cy.url().should('contain', '***');
```
		
![image](https://github.com/user-attachments/assets/9af44468-3608-4098-98c8-3820f1cd8fc0)
	

### ✅ What did you expect to see?

I am expecting to redirect to my base URL after the authentication is completed successfully.

### 📦 Which tool/library version are you using?

node: v20.12.2
cypress: 12.10.0
@badeball/cypress-cucumber-preprocessor: 16.0.3

**Comment by kieran-ryan** [comment]
Hey @viditasatam, thanks for your issue. This appears to be an issue within the automation code itself, rather than this project ([the Cucumber Visual Studio Code extension](https://github.com/cucumber/vscode)) - if I understood correctly. Could you clarify whether that is the case?

If that's suitable, perhaps you might advise if any of these options are appropriate based on scope of the issue: if relates to the Cucumber preprocessor to raise in the [cypress-cucumber-preprocessor](https://github.com/badeball/cypress-cucumber-preprocessor); raise in [cypress](https://github.com/cypress-io/cypress) if relates to the Cypress framework; advise whether relates to the [Cucumber JavaScript implementation](https://github.com/cucumber/cucumber-js) and I can move the issue to that project; or otherwise to try some of our [Cucumber support channels](https://cucumber.io/docs/community/get-in-touch/#slack) or [discussions board](https://github.com/orgs/cucumber/discussions). Hope this may be of some help to direct your query and resolve the issue for you 👌

**Comment by viditasatam** [comment]
I dont think its an issue with [Cucumber Visual Studio Code extension](https://github.com/cucumber/vscode)

I am not sure whether its a code issue or cypress issue since my configuration looks fine according to me, still the test fails and I am unable to redirect to baseurl once I login to microsoft azure account. I need help from the experts and hence, I have raised the issue here

**Comment by kieran-ryan** [comment]
Thanks for your response @viditasatam (though can no longer observe from the issue itself)

Observe you have now raised through our [GitHub discussions board](https://github.com/orgs/cucumber/discussions/2183) outlined above - hope this can yield an answer; but otherwise also try one of the other mentioned forums. What I've also often found helpful is to construct a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) in a separate repository for someone to be able to reproduce and debug the issue; though this can be tricky in circumstances such as yours where we're relying on external connections, etc.

Closing as would be unable to resolve within the scope of this project; however feel free to keep us updated here on any developments 👍
