### ISSUE TITLE
Add Cucumber icon for `.feature` files

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/vscode#28]
I think this is done by contributing a [File Icon Theme](https://code.visualstudio.com/api/extension-guides/file-icon-theme)

**Comment by aslakhellesoy** [comment]
Alternatively, or perhaps *additionally*, we could encourage the use of [vscode-icons](https://github.com/vscode-icons/vscode-icons). We should send a PR with an updated icon for [cucumber](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles#cucumber)

**Comment by 10xtechie** [comment]
Hello @aslakhellesoy, 
Where can I find the latest official _**`Cucumber`**_ logo in **_svg_** format? Once I have it, I can create a PR on [File Icon Theme](https://code.visualstudio.com/api/extension-guides/file-icon-theme) and [vscode-icons](https://github.com/vscode-icons/vscode-icons).
However, there are other vscode icon extensions such as [vscode-material-icon-theme](https://github.com/PKief/vscode-material-icon-theme) etc. I guess we will have to find a way to ship the **_`Cucumber`_** icon with our [vscode extension](https://github.com/cucumber/vscode), so that the icon will be automatically associated with the .feature files.

**Comment by phuongwd** [comment]
The Cucumber icon for .feature files will not work if I installed the Cucumber [vscode extension](https://github.com/cucumber/vscode).
Please see the video

https://user-images.githubusercontent.com/2460806/177675314-435a4703-d53b-4a91-9064-8b655b409930.mov

**Comment by aslakhellesoy** [comment]
Hi @10xtechie - sorry for the late reply! You can find a copy of the official Cucumber logo as SVG here: https://github.com/cucumber/html-formatter/blob/main/javascript/logo.svg

**Comment by 10xtechie** [comment]
Hello @aslakhellesoy,
Thanks for your reply! No problem! 
The above official Cucumber logo is now part of [vscode-icons](https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_cucumber.svg) . Please take a look.

**Comment by aslakhellesoy** [comment]
Thanks @10xtechie! I'll close this issue then :-)
